# Generated by Django 5.2 on 2025-04-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('synopsis', models.TextField(default='No synopsis')),
            ],
        ),
    ]
